# Generated by Django 3.2.3 on 2021-06-04 06:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default/default_avatar.png', upload_to='profiles'),
        ),
    ]
